version: '3'
services:

  php-fpm:
    build: ./data/php-fpm
    working_dir: /www
    volumes:
      - './data/html:/www:rw'
      - './data/log:/usr/local/var/log:rw'

  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './data/log:/var/log:rw'
      - './data/html:/www:rw'
      - './data/nginx:/etc/nginx/conf.d:ro'
      - './data/certbot/www:/var/www/certbot:ro'
      - './data/certbot/conf:/etc/letsencrypt:ro'
    depends_on:
      - php-fpm
      - certbot

  certbot:
    image: certbot/certbot
    command: 'renew'
    volumes:
      - './data/log:/var/log:rw'
      - './data/certbot/www:/var/www/certbot:rw'
      - './data/certbot/conf:/etc/letsencrypt:rw'


