FROM php:8.0-fpm-alpine3.15
WORKDIR "/www"

# Installing dependencies for PHP modules
#RUN apk update && apk add --no-cache \
#         libzip \
#         libzip-dev \
#         libpng \
#         libpng-dev
#RUN rm -rf /var/cache/apk/

# Install and enable PHP modules
#RUN docker-php-ext-install zip gd ; docker-php-ext-enable zip gd

CMD ["php-fpm"]*
